-- GRADES
INSERT INTO grades (name, description, order_index) VALUES ('Nursery', '', 1) ON CONFLICT DO NOTHING;
INSERT INTO grades (name, description, order_index) VALUES ('Grade 1', '', 2) ON CONFLICT DO NOTHING;
INSERT INTO grades (name, description, order_index) VALUES ('Grade 3', '', 4) ON CONFLICT DO NOTHING;
INSERT INTO grades (name, description, order_index) VALUES ('Grade 4', '', 5) ON CONFLICT DO NOTHING;
INSERT INTO grades (name, description, order_index) VALUES ('Grade 5', '', 6) ON CONFLICT DO NOTHING;
INSERT INTO grades (name, description, order_index) VALUES ('Grade 2', '', 3) ON CONFLICT DO NOTHING;
INSERT INTO grades (name, description, order_index) VALUES ('standerd 6', '', 20) ON CONFLICT DO NOTHING;

-- SUBJECTS
INSERT INTO subjects (id, name, description, icon, color) VALUES ('18', 'Bangla', '', '', '#000000') ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, name, description, icon, color) VALUES ('30', 'English', '', '', '#000000') ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, name, description, icon, color) VALUES ('31', 'Math', '', '', '#000000') ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, name, description, icon, color) VALUES ('33', 'Math', '', '', '#000000') ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, name, description, icon, color) VALUES ('34', 'English', '', '', '#000000') ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, name, description, icon, color) VALUES ('35', 'Bangla', '', '', '#000000') ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, name, description, icon, color) VALUES ('36', 'Science', '', '', '#000000') ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, name, description, icon, color) VALUES ('37', 'English', '', '', '#000000') ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, name, description, icon, color) VALUES ('38', 'গণিত বিষয়বস্তু', '', '', '#000000') ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, name, description, icon, color) VALUES ('39', 'বাংলা', '', '', '#000000') ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, name, description, icon, color) VALUES ('40', 'English', '', '', '#000000') ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, name, description, icon, color) VALUES ('41', 'Math', '', '', '#000000') ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, name, description, icon, color) VALUES ('42', 'Bangla', '', '', '#000000') ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, name, description, icon, color) VALUES ('43', 'Bangla', '', '', '#000000') ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, name, description, icon, color) VALUES ('44', 'Math', '', '', '#000000') ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, name, description, icon, color) VALUES ('45', 'English', '', '', '#000000') ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, name, description, icon, color) VALUES ('46', 'Basic Science', '', '', '#000000') ON CONFLICT (id) DO NOTHING;
INSERT INTO subjects (id, name, description, icon, color) VALUES ('47', 'gcesxet', '', '', '#000000') ON CONFLICT (id) DO NOTHING;

-- CONTENTS
INSERT INTO contents (id, title, subtitle, description, content_type, youtube_link, file_url, is_published, order_index, content_data) VALUES ('74557c04-511b-40da-81f3-189ce84d4768', 'bangla', NULL, ' Practice of sum from 0 to 20 Practice of sum from 0 to 20 Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20', 'video', 'https://www.youtube.com/watch?v=OCh0Xabsg4w', NULL, true, 1, '{"pages":[{"title":"bangla","file_url":"","description":" Practice of sum from 0 to 20 Practice of sum from 0 to 20 Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20Practice of sum from 0 to 20","content_type":"youtube","youtube_link":"https://www.youtube.com/watch?v=OCh0Xabsg4w"}]}'::jsonb) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, description = EXCLUDED.description, youtube_link = EXCLUDED.youtube_link, is_published = EXCLUDED.is_published;
INSERT INTO contents (id, title, subtitle, description, content_type, youtube_link, file_url, is_published, order_index, content_data) VALUES ('ebacbcc0-3fcb-41f1-88ae-f8eaf9b138de', 'Biral keno Shara din ghumay?', NULL, 'Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? ', 'video', 'https://youtu.be/BjDozn9EQ8k', NULL, true, 1, '{"pages":[{"title":"Biral keno Shara din ghumay?","file_url":"","description":"Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? Biral keno Shara din ghumay? ","content_type":"youtube","youtube_link":"https://youtu.be/BjDozn9EQ8k"}]}'::jsonb) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, description = EXCLUDED.description, youtube_link = EXCLUDED.youtube_link, is_published = EXCLUDED.is_published;
INSERT INTO contents (id, title, subtitle, description, content_type, youtube_link, file_url, is_published, order_index, content_data) VALUES ('e3814ecc-f092-41f3-a714-f11fdb5972c0', 'Alphabets A–Z', NULL, 'Welcome to Alphabet Adventure! Let’s learn the letters A to Z. A is for Apple 🍎, B is for Ball ⚽, C is for Cat 🐱. Each letter has a sound and a word. When you put letters together, they make words, and words help us talk and read. Let’s sing the ABC song together and become alphabet heroes!', 'video', 'https://youtu.be/kpy6QEAuLJw', NULL, true, 1, '{}'::jsonb) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, description = EXCLUDED.description, youtube_link = EXCLUDED.youtube_link, is_published = EXCLUDED.is_published;
INSERT INTO contents (id, title, subtitle, description, content_type, youtube_link, file_url, is_published, order_index, content_data) VALUES ('47ecf72f-3c72-4a1a-b77f-2fe0cea0362b', 'অ আ ই ঈ', NULL, 'আসো বাচ্চারা, আমরা বাংলা বর্ণমালা শিখি। অ – অজগর, আ – আম, ই – ইলিশ, ঈ – ঈগল। প্রতিটা বর্ণের সাথে একটা শব্দ আছে। যেমন অ=অজগর 🐍, আ=আম 🍋। প্রতিদিন ৫টা করে বর্ণ শিখলে অ–ঔ পর্যন্ত সব শিখে ফেলবে। খুব সহজ!', 'video', 'https://youtu.be/h6cSa-iR_Xw', NULL, true, 2, '{}'::jsonb) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, description = EXCLUDED.description, youtube_link = EXCLUDED.youtube_link, is_published = EXCLUDED.is_published;
INSERT INTO contents (id, title, subtitle, description, content_type, youtube_link, file_url, is_published, order_index, content_data) VALUES ('c2b6a49d-a62e-447c-81cc-560764292622', 'সংখ্যা ১–১০', NULL, 'আজ আমরা বাংলা সংখ্যা শিখব। ১ = এক, ২ = দুই, ৩ = তিন, ৪ = চার, ৫ = পাঁচ… ১০ পর্যন্ত। তুমি যদি ৩টা কলা 🍌 আর ২টা আপেল 🍎 ধরো, মোট কয়টা ফল হলো? ৫টা! এইভাবে সংখ্যা ব্যবহার হয় আমাদের চারপাশে।', 'video', 'https://youtu.be/DR-cfDsHCGA', NULL, true, 1, '{}'::jsonb) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, description = EXCLUDED.description, youtube_link = EXCLUDED.youtube_link, is_published = EXCLUDED.is_published;
INSERT INTO contents (id, title, subtitle, description, content_type, youtube_link, file_url, is_published, order_index, content_data) VALUES ('33f12325-559d-403e-83d9-2cb3b07e3c7d', 'Addition with Carry', NULL, 'Today we will learn how to add numbers like 47 + 38. First, add the ones: 7 + 8 = 15. Write 5, carry 1 to the tens. Now add the tens: 4 + 3 + 1 = 8. So, the answer is 85.', 'video', 'https://youtu.be/_NN8g2jWIAs', NULL, true, 1, '{}'::jsonb) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, description = EXCLUDED.description, youtube_link = EXCLUDED.youtube_link, is_published = EXCLUDED.is_published;
INSERT INTO contents (id, title, subtitle, description, content_type, youtube_link, file_url, is_published, order_index, content_data) VALUES ('1eaa6a0d-951d-43db-87c6-6329a82e14d6', 'Opposite Words', NULL, 'Some words have opposite meanings. For example:

Big ↔ Small

Hot ↔ Cold

Happy ↔ Sad

Day ↔ Night
Learning opposites helps us understand language better.', 'video', 'https://youtu.be/LF3crlV28xA', NULL, true, 1, '{}'::jsonb) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, description = EXCLUDED.description, youtube_link = EXCLUDED.youtube_link, is_published = EXCLUDED.is_published;
INSERT INTO contents (id, title, subtitle, description, content_type, youtube_link, file_url, is_published, order_index, content_data) VALUES ('170543a8-3d4b-4d46-b70f-40635e6fbcb4', 'পরিবেশ পরিচিতি', NULL, 'আমাদের চারপাশে গাছ, ফুল, নদী, পাখি, পশুপাখি, আকাশ—সব মিলে পরিবেশ তৈরি হয়। পরিবেশকে সুন্দর রাখতে আমাদের গাছ লাগাতে হবে, ময়লা ফেলতে হবে না, আর প্রাণীদের ভালোবাসতে হবে।', 'video', 'https://youtu.be/7WLdq4FuXyE', NULL, true, 1, '{}'::jsonb) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, description = EXCLUDED.description, youtube_link = EXCLUDED.youtube_link, is_published = EXCLUDED.is_published;
INSERT INTO contents (id, title, subtitle, description, content_type, youtube_link, file_url, is_published, order_index, content_data) VALUES ('8fadd035-76a9-4761-bdfd-1ffb20dfb21a', 'Our Five Senses', NULL, 'We have five senses:

Eyes help us see 👀

Ears help us hear 👂

Nose helps us smell 👃

Tongue helps us taste 👅

Skin helps us feel ✋
All senses are important to understand the world around us.', 'video', 'https://youtu.be/5cNnqBWDOcU', NULL, true, 1, '{}'::jsonb) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, description = EXCLUDED.description, youtube_link = EXCLUDED.youtube_link, is_published = EXCLUDED.is_published;
INSERT INTO contents (id, title, subtitle, description, content_type, youtube_link, file_url, is_published, order_index, content_data) VALUES ('f597b946-0fc2-4401-a252-db126407fece', 'Count and Write Numbers - Football Game', NULL, '⚽ ফুটবল গণনা খেলা: প্রতিটি বক্সে থাকা ফুটবলগুলো গণনা করে সঠিক সংখ্যা লিখুন। এই ইন্টারেক্টিভ গেমে ছাত্ররা ফুটবল গণনা করে সংখ্যা লিখতে পারবে এবং সাথে সাথে উত্তর চেক করতে পারবে।', 'image', NULL, NULL, true, 1, '{"pages":[{"title":"Count and Write Numbers - Football Game","file_url":"https://example.com/counting-worksheet.jpg","description":"⚽ ফুটবল গণনা খেলা: প্রতিটি বক্সে থাকা ফুটবলগুলো গণনা করে সঠিক সংখ্যা লিখুন। এই ইন্টারেক্টিভ গেমে ছাত্ররা ফুটবল গণনা করে সংখ্যা লিখতে পারবে এবং সাথে সাথে উত্তর চেক করতে পারবে।","content_type":"image"}]}'::jsonb) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, description = EXCLUDED.description, youtube_link = EXCLUDED.youtube_link, is_published = EXCLUDED.is_published;
INSERT INTO contents (id, title, subtitle, description, content_type, youtube_link, file_url, is_published, order_index, content_data) VALUES ('b3d2d1f3-458b-4175-83ec-5d661957f334', 'Funny Story 2', NULL, 'একদিন এক ভিক্ষুক রাস্তায় দাঁড়িয়ে ভিক্ষা করছিল। এই দেখে এক লোকের খুব দয়া হল।
সে ভিক্ষুকের কাছে গিয়ে বলল: তুমি যদি ভিক্ষাবৃত্তি ছেড়ে দাও, তাহলে তোমাকে আমি মাসে ১০০০ টাকা করে দেব।
জবাবে ভিক্ষুক লোকটিকে বলল: তুমি যদি আমার সঙ্গে ভিক্ষা করো তাহলে প্রতি মাসে আমি তোমাকে ৫০০০ টাকা দেব।', 'video', 'https://youtu.be/qsO5jVrzoas', 'https://th-thumbnailer.cdn-si-edu.com/5KaXRE4bPNZdCb3noUuEbT2CF3c=/970x545/https://tf-cmsv2-smithsonianmag-media.s3.amazonaws.com/filer/d6/7d/d67d186f-f5f3-4867-82c5-2c772120304f/thanos-snap-featured-120518-2.jpg', true, 1, '{"pages":[{"title":"Funny Story 2","file_url":"https://th-thumbnailer.cdn-si-edu.com/5KaXRE4bPNZdCb3noUuEbT2CF3c=/970x545/https://tf-cmsv2-smithsonianmag-media.s3.amazonaws.com/filer/d6/7d/d67d186f-f5f3-4867-82c5-2c772120304f/thanos-snap-featured-120518-2.jpg","description":"একদিন এক ভিক্ষুক রাস্তায় দাঁড়িয়ে ভিক্ষা করছিল। এই দেখে এক লোকের খুব দয়া হল।\nসে ভিক্ষুকের কাছে গিয়ে বলল: তুমি যদি ভিক্ষাবৃত্তি ছেড়ে দাও, তাহলে তোমাকে আমি মাসে ১০০০ টাকা করে দেব।\nজবাবে ভিক্ষুক লোকটিকে বলল: তুমি যদি আমার সঙ্গে ভিক্ষা করো তাহলে প্রতি মাসে আমি তোমাকে ৫০০০ টাকা দেব।একদিন এক ভিক্ষুক রাস্তায় দাঁড়িয়ে ভিক্ষা করছিল। এই দেখে এক লোকের খুব দয়া হল।\nসে ভিক্ষুকের কাছে গিয়ে বলল: তুমি যদি ভিক্ষাবৃত্তি ছেড়ে দাও, তাহলে তোমাকে আমি মাসে ১০০০ টাকা করে দেব।\nজবাবে ভিক্ষুক লোকটিকে বলল: তুমি যদি আমার সঙ্গে ভিক্ষা করো তাহলে প্রতি মাসে আমি তোমাকে ৫০০০ টাকা দেব।একদিন এক ভিক্ষুক রাস্তায় দাঁড়িয়ে ভিক্ষা করছিল। এই দেখে এক লোকের খুব দয়া হল।\nসে ভিক্ষুকের কাছে গিয়ে বলল: তুমি যদি ভিক্ষাবৃত্তি ছেড়ে দাও, তাহলে তোমাকে আমি মাসে ১০০০ টাকা করে দেব।\nজবাবে ভিক্ষুক লোকটিকে বলল: তুমি যদি আমার সঙ্গে ভিক্ষা করো তাহলে প্রতি মাসে আমি তোমাকে ৫০০০ টাকা দেব।একদিন এক ভিক্ষুক রাস্তায় দাঁড়িয়ে ভিক্ষা করছিল। এই দেখে এক লোকের খুব দয়া হল।\nসে ভিক্ষুকের কাছে গিয়ে বলল: তুমি যদি ভিক্ষাবৃত্তি ছেড়ে দাও, তাহলে তোমাকে আমি মাসে ১০০০ টাকা করে দেব।\nজবাবে ভিক্ষুক লোকটিকে বলল: তুমি যদি আমার সঙ্গে ভিক্ষা করো তাহলে প্রতি মাসে আমি তোমাকে ৫০০০ টাকা দেব।একদিন এক ভিক্ষুক রাস্তায় দাঁড়িয়ে ভিক্ষা করছিল। এই দেখে এক লোকের খুব দয়া হল।\nসে ভিক্ষুকের কাছে গিয়ে বলল: তুমি যদি ভিক্ষাবৃত্তি ছেড়ে দাও, তাহলে তোমাকে আমি মাসে ১০০০ টাকা করে দেব।\nজবাবে ভিক্ষুক লোকটিকে বলল: তুমি যদি আমার সঙ্গে ভিক্ষা করো তাহলে প্রতি মাসে আমি তোমাকে ৫০০০ টাকা দেব।একদিন এক ভিক্ষুক রাস্তায় দাঁড়িয়ে ভিক্ষা করছিল। এই দেখে এক লোকের খুব দয়া হল।\nসে ভিক্ষুকের কাছে গিয়ে বলল: তুমি যদি ভিক্ষাবৃত্তি ছেড়ে দাও, তাহলে তোমাকে আমি মাসে ১০০০ টাকা করে দেব।\nজবাবে ভিক্ষুক লোকটিকে বলল: তুমি যদি আমার সঙ্গে ভিক্ষা করো তাহলে প্রতি মাসে আমি তোমাকে ৫০০০ টাকা দেব।","content_type":"youtube","youtube_link":"https://youtu.be/qsO5jVrzoas"}]}'::jsonb) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle, description = EXCLUDED.description, youtube_link = EXCLUDED.youtube_link, is_published = EXCLUDED.is_published;

-- Done! Copy the SQL above and run it in Supabase SQL Editor
